logging:
  level.*:
    org.springframework.web.client.RestTemplate: INFO
    com.application.document: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: TRACE
  file:
    name: logs/document-app.log

server:
  port: 8080
  servlet:
    context-path: /document

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/document_api
    driverClassName: org.postgresql.Driver
    username: postgres
    password: pass
    hikari:
      auto_commit: false


project-info:
  packages:
    - name: document
      isProjectAlive: true

