logging:
  level.*:
    org.springframework.web.client.RestTemplate: INFO
    com.application.document: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: TRACE
  file:
    name: logs/document-app.log

server:
  port: 8080
  servlet:
    context-path: /document

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update


project-info:
  packages:
    - name: document
      isProjectAlive: true

